---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: fast-food-catalog
  main:
    lazy-initialization: true
  jmx:
    enabled: false
  mvc:
    problem-details:
      enabled: true
    jackson:
      default-property-inclusion: non_null
  data:
    rest:
      default-media-type: application/json
    mongodb:
        uri: ${MONGODB_URL}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

springdoc:
  swagger-ui:
    urls:
      - url: /catalog/v3/api-docs
        name: Fast Food Catalog API
      - url: /v3/api-docs
        name: Fast Food Catalog API Local

