apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-pod-identity-deployment-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/fast_food-catalog/mongo"
        objectType: "secretsmanager"
        jmesPath:
          - path: MONGO_URL
            objectAlias: MONGO_URL
    usePodIdentity: "true"
  secretObjects:
    - secretName: catalog-secret
      type: Opaque
      data:
        - objectName: MONGO_URL
          key: MONGODB_URL